In [1]:
import numpy as np

Question 1

In [2]:
greyChannel = np.array([117, 113, 93, 89, 97, 90, 86, 83, 80, 79, 71, 76, 78, 84, 83, 79, 74, 68, 65, 64, 62, 68, 60, 59, 58]).reshape(5, 5)

In [16]:
normalizedValue = greyChannel/255
print(normalizedValue)

[[0.45882353 0.44313725 0.36470588 0.34901961 0.38039216]
 [0.35294118 0.3372549  0.3254902  0.31372549 0.30980392]
 [0.27843137 0.29803922 0.30588235 0.32941176 0.3254902 ]
 [0.30980392 0.29019608 0.26666667 0.25490196 0.25098039]
 [0.24313725 0.26666667 0.23529412 0.23137255 0.22745098]]


Question 2

In [9]:
redChannel = np.array([117, 161, 138, 139, 117, 161, 152, 125, 134, 106, 146, 142, 123, 118, 101, 133, 140, 119, 1190, 96, 138, 122, 1212, 101, 94]).reshape(5, 5)
blueChannel = np.array([ 97, 86, 75, 67, 86, 80, 75, 67, 57, 72, 72, 61, 77, 76, 62, 60, 55, 60, 56, 48, 59, 51, 48, 47, 47]).reshape(5, 5)
greenChannel = np.array([24, 21, 13, 27, 22, 18, 21, 8, 31, 20, 11, 20, 14, 22, 17, 6, 24, 16, 29, 17, 19, 12, 12, 14, 19]).reshape(5,5)

In [13]:
relativeLuminance = (0.21*redChannel + 0.72*greenChannel + 0.007*blueChannel)/255
print(relativeLuminance)

[[0.16678039 0.19424314 0.15241176 0.1925451  0.16083137]
 [0.18560784 0.18652941 0.12736863 0.19944706 0.14574118]
 [0.15327059 0.17508627 0.14293725 0.16138039 0.13287843]
 [0.12811765 0.18456863 0.14482353 1.06341961 0.12837647]
 [0.16891373 0.13575294 1.03331765 0.12399608 0.13234902]]


Question 3