In [46]:
import numpy as np
from scipy.signal import convolve2d
from scipy.ndimage import median_filter

In [5]:
im = np.array([0, 0, 0, 0, 0, 0, 10, 10, 10, 0, 0, 10, 10, 10, 0, 0, 10, 0, 10, 0, 10, 0, 0, 0, 0]).reshape(5,5)

1a

In [49]:
window_size = 3
mean_kernel = np.ones([window_size, window_size]) / (window_size*window_size)
gaussian_kernel = 0.0625*np.array([1, 2, 1, 2, 4, 2, 1, 2, 1]).reshape(window_size,window_size)

mean_image = np.round(convolve2d(im, mean_kernel, mode='valid'))
gaussian_image = np.round(convolve2d(im, gaussian_kernel, mode='valid'))
median_image = median_filter(im, size=window_size)

In [50]:
print("Mean")
print(mean_image)
print("\nGaussian")
print(gaussian_image)
print("\nMedian")
print(median_image)

Mean
[[4. 7. 4.]
 [6. 9. 6.]
 [4. 6. 3.]]

Gaussian
[[6. 8. 6.]
 [7. 9. 7.]
 [5. 5. 4.]]

Median
[[ 0  0  0  0  0]
 [ 0  0 10  0  0]
 [ 0 10 10 10  0]
 [ 0  0 10  0  0]
 [10  0  0  0  0]]


3a

In [53]:
im1_p1 = np.array([0, 0, 0, 0, 10, 10, 0, 10, 10]).reshape(3,3)
im1_p2 = np.array([10, 20, 20, 10, 20, 20, 10, 10, 10]).reshape(3,3)
im2_p1 = np.array([10, 10, 10, 10, 20, 20, 10, 20, 20]).reshape(3,3)
im2_p2 = np.array([0, 10, 10, 0, 10, 10, 0, 0, 0]).reshape(3,3)

In [66]:
def calculate_ssd(im1, im2):
    ssd = 0
    for i in range(3):
        for j in range(3):
            ssd = ssd + (im1[i, j] - im2[i, j])**2
    return ssd

In [69]:
print("SSD between im1 patch 1 & im2 patch 1")
print(calculate_ssd(im1_p1, im2_p1))
print("SSD between im1 patch 1 & im2 patch 2")
print(calculate_ssd(im1_p1, im2_p2))
print("SSD between im1 patch 2 & im2 patch 2")
print(calculate_ssd(im1_p2, im2_p2))

SSD between im1 patch 1 & im2 patch 1
900
SSD between im1 patch 1 & im2 patch 2
400
SSD between im1 patch 2 & im2 patch 2
900


In [72]:
# Normalize by subtracting the mean. Dividing by standard deviation is not used as subtracting the mean is sufficient for this case.
print("SSD between im1 patch 1 & im2 patch 1")
print(calculate_ssd(im1_p1-np.mean(im1_p1), im2_p1-np.mean(im2_p1)))
print("SSD between im1 patch 1 & im2 patch 2")
print(calculate_ssd(im1_p1-np.mean(im1_p1), im2_p2-np.mean(im2_p2)))
print("SSD between im1 patch 2 & im2 patch 2")
print(calculate_ssd(im1_p2-np.mean(im1_p2), im2_p2-np.mean(im2_p2)))

print("Im1 patch 1 matches Im2 patch 1, and Im2 patch 2 matches Im2 patch 2")

SSD between im1 patch 1 & im2 patch 1
0.0
SSD between im1 patch 1 & im2 patch 2
400.0
SSD between im1 patch 2 & im2 patch 2
0.0
Im1 patch 1 matches Im2 patch 1, and Im2 patch 2 matches Im2 patch 2
